LST_IS_INFL_TOKENS = ['inflation', 'inflationsrate']
LST_SPACY_POS = ['PROPN', 'NOUN', 'AJD']

DICT_NARRATIVES = {
    "D_inflation": {
        'g1': ["kaufpreis", "preis", "verbraucherpreis",],
        'g2': [ "inflation", "inflationsrate"],
        'g3': ['teuerung', 'preissteigerung'],
        'g4': ['inflationserwartung', "zinserwartung"],
    },
    "S_labour": {
        'g1': ["mitarbeiter", "arbeitnehmer"],
        'g2': ["gehalt", "lohn", "gehaltssteigerung", "lohnsteigerung"],
        'g3': ["arbeitslosigkeit", "arbeitslosenquote", "arbeitslosenzahl"],
        'g4': ['beschäftigter', 'beschäftigung'],

    },
    "S_supply_chain": {
        'g1': ["supply", "chain"],
        'g2': ["lieferkette"],
        'g3': ["import", "handel"],
        'g4': ["halbleiter"],
        "g5": ["engpass"],
    },
    "S_production": {
        'g1': ['produktion', 'hersteller'],
        "g2": ['produktionskapazität'],
        'g3': ['kosten', "produktionskosten"],
        "g4": ["angebot", "angebotsschock", "angebotsknappheit"],
        
    },
    "S_war": {
        'g1': ['russland', 'ukraine'],
        'g2': ['krieg', 'konflikt'],
        'g3': ['sanktion'],
    },
    "S_energy": {
        'g1': ['nord', 'stream', 'pipeline'],
        'g2': ['gas', 'erdgas', 'preis'],
        'g3': ['strom', 'öl', 'preis'],
        'g4': ['energie', 'preis'], 
    },
    "S_profits" : {

        "g1": ["profit", "profitabilität"],
        "g2": ["gewinn", "unternehmensgewinn", "gewinnabschöpfung", "gewinnmitnahm", "rekordgewinn"],
        "g3": ["übergewinnsteuer", "übergewinn"],
        "g4": ["gierflation"],
    },
    'S_pandemic': {
        'g1': ['corona', 'covid'],
        'g2': ['pandemie', 'virus'],
        'g3': ['lockdown', 'lockdowns'],
    },    
    "M_policy": {
        'g1': ["zins", "zinsrate"],
        'g2': ['geldpolitik'],
        'g3': ['notenbank', 'zentralbank'],
        'g4': ['fed', 'ezb'],
        'g5': ["christine", 'lagarde', "jerome", "powell", "mario", "draghi"],
    },
    "M_policy_counter": {
        'g1': ['niedrigzinsphase'],
        'g2': ['quantiative', 'easing'],
        'g3': ["anleihenkauf", "anleihenkaufprogramm", "staatsanleihenkaufprogramm", "kaufprogramm"],
        "g4": ["pepp"],
    },
    "M_crisis": {
        'g1': ['krise'],
        'g2': ['rezession'],
        'g3': ['risiko'],
    },
    "D_gov": {
        'g1': ["konjunkturprogramm"],
        'g2': ["subvention", "staatshilfe"],
        "g3": ["staatsverschuldung", "schuldenlast", "schuldenbremse", "schuldenkrise"],
        "g4": ["coronahilfe"],
        "g5": ["kurzarbeit", "kurzarbeitergeld"],
        "g6": ["mehrwertsteuersenkung", "steuersenkung"],
    },
    "D_hh_spend": {
        'g1': ['nachfrage', "nachfrageschub"], 
        'g2': ['konsum', 'ausgabe'],
        'g3': ["haushalt", "verbraucher", "kunde"],
        'g4': ['lebensmittel'],
    },

}

"""
mensch, markt, folge, welt, ziel, höhe, sinn, jahrhundert
"""

LST_FREQUENT_NON_MEANING = [
        
        'prozent',
         'euro',
         'million',
         'milliarde',
         'deutschland',
         'deutsch',
         'land',
         'firma',
         'frage',
         'zahl',
         'woche',
         'monat',
         'stadt',
         'bereich',
         'seite',
         'datum',
         'quartal',
         'tonne',
         'zeit',
         'entwicklung',
         'standort',
         'vergleich',
         'jahr',
         'experte',
         'anfangm',
         'lage',
         'thema',
         'anteil',
         'blick',
         'weg',
         'meinungen',
         'punkt',
         'januar',
         'september',
         'maßnahme',
         'juni',
         'situation',
         'hälfte',
         'angabe',
         'jahrzehnt',
         'juli',
         'institut',
         'region',
         'vorjahr',
         'frau',
         'april',
         'kilometer',
         'dienstag',
         'system',
         'familie',
         'mitt',
         'gespräch',
         'mai',
         'niveau',
         'oktober',
         'lösung',
         'modell',
         'idee',
         'dezember',
         'prognose',
         'papier',
         'drittel',
         'schnitt',
         'mal',
         'strategie',
         'november',
         'platz',
         'mittwoch',
         'montag',
         'stelle',
         'august',
         'februar',
         'teil',
         'stunde',
         'hand',
         'name',
         'freitag',
         'halbjahr',
         'umfrage',
         'prozentpunkt',
         'stand',
         'wort',
         'summe'
]